### ISSUE TITLE
JIT provisioning and persisting User doesn't change anything in the database

### ISSUE THREAD

**Issue by likou31** [nbgrp/onelogin-saml-bundle#42]
Hello !

So I'm having with using the JIT provisioning and the persist_user.

What I'm trying to achieve is that at every connexion of the user, if in the attributes "roles" something has changed, than it changes its roles into the database.

What my code looks like :

in the security.yaml ->

```
providers:
        saml_provider:
            ##  Basic provider instantiates a user with identifier and default roles
            entity:
                class: App\Entity\User
                property: email

...


main:
            pattern: ^/
            provider: saml_provider
            saml:
                ##  Match SAML attribute 'uid' with user identifier.
                ##  Otherwise, used \OneLogin\Saml2\Auth::getNameId() method by default.
                identifier_attribute: email
                check_path: saml_acs
                login_path: saml_login
                user_factory: saml_user_factory
                persist_user: true
            logout:
                path: saml_logout
```

in the services.yaml ->

```
services:
    saml_user_factory:
          class: App\Security\UserFactory
```

And in my UserFactory.php ->

```
 public function createUser(string $identifier, array $attributes): UserInterface
 {
        $user = new User();
        $user->setEmail($attributes['email'][0]);
        $user->setFirstname($attributes['firstname'][0]);
        $user->setLastname($attributes['lastname'][0]);
        $user->setTrigram($attributes['trigram'][0]);

        $rolesAttributes = $attributes['roles'];
        if ($_ENV['APP_ENV'] == 'prod') {
            $user->setRoles($this->setProdRoles($rolesAttributes));
        } else if ($_ENV['APP_ENV'] == 'dev') {
            $user->setRoles($this->setDevRoles($rolesAttributes));
        } else {
            $user->setRoles([]);
        }
        return $user;
}
```

And then for an exemple of the prod roles function ->

```
public function setProdRoles(array $rolesAttributes): array
    {
        $roles = [];
        if (in_array('roles1', $rolesAttributes)) {
            $roles[] = 'ROLE_USER';
        }
        if (in_array('roles2', $rolesAttributes)) {
            $roles[] = 'ROLE_TEST1';
        }
        if (in_array('roles3', $rolesAttributes)) {
            $roles[] = 'ROLE_TEST2';
        }
        return $roles;
    }
```

For the use case, what happens is that when a user load for the first time on my application, and in his attribute roles he has only "roles1", then he's going to have 'ROLE_USER' in the database.
But then, in the saml server we add the 'roles2', and what happens is that when he reconnects to the website, he doesn't have the 'ROLE_TEST1' in the database, even though we tried to delete cookies, etc... I have to manually change in the database...

How can i achieve this please ?
